all:
	g++ -g -c CaioCalculator/Calculator/CaioCalculator.cpp
	g++ -g -c CaioCalculator/CPU/CaioCpu.cpp
	g++ -g -c CaioCalculator/Display/CaioDisplay.cpp
	g++ -g -c CaioCalculator/Keyboard/CaioKeyboard.cpp
	g++ -g -c interface.cpp
	g++ -g -c main.cpp
	g++ -o main *.o

clean:
	rm ./*.o
	rm main